apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs/finalizers
    verbs:
      - update
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs/status
    verbs:
      - get
      - patch
      - update
  # 添加對 CronJob 資源的權限
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
      - get
      - list
      - watch
      - update
