apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dr-cronjob-crd-manager-role
rules:
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs/finalizers
    verbs:
      - update
  - apiGroups:
      - batch.104corp.org
    resources:
      - cronjoblabelconfigs/status
    verbs:
      - get
      - patch
      - update
  # 新增對 batch API 組的權限
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - update
